server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:h2db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    databse-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2
