CREATE TABLE CONFERENCE_ROOM
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) DEFAULT '' NOT NULL,
    CAPACITY INT NOT NULL
    );

CREATE TABLE MAINTENANCE_TIMINGS
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    START_TIME TIME DEFAULT '' NOT NULL,
    END_TIME TIME NOT NULL
    );


CREATE TABLE BOOKING_DETAILS
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    START_TIME TIME DEFAULT '' NOT NULL,
    END_TIME TIME NOT NULL,
    ROOM_ID INT NOT NULL,
    foreign key (ROOM_ID) REFERENCES CONFERENCE_ROOM(ID)
    );